<a href="https://colab.research.google.com/github/amirulaimanr/AIBE-Exercise-Learning/blob/main/AIBE_Social_Ads_LinearModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import seaborn as sns
import numpy as np

In [8]:
df = pd.read_excel("sample_data/social_ads_dataset.xlsx")

In [10]:
df

     audience_id  google  facebook  instagram  sales  size
0              1   230.1      37.8       69.2   22.1     1
1              2    44.5      39.3       45.1   10.4     0
2              3    17.2      45.9       69.3    9.3     0
3              4   151.5      41.3       58.5   18.5     0
4              5   180.8      10.8       58.4   12.9     1
..           ...     ...       ...        ...    ...   ...
195          196    38.2       3.7       13.8    7.6     0
196          197    94.2       4.9        8.1    9.7     0
197          198   177.0       9.3        6.4   12.8     0
198          199   283.6      42.0       66.2   25.5     0
199          200   232.1       8.6        8.7   13.4     1

[200 rows x 6 columns]

In [11]:
df.head()

   audience_id  google  facebook  instagram  sales  size
0            1   230.1      37.8       69.2   22.1     1
1            2    44.5      39.3       45.1   10.4     0
2            3    17.2      45.9       69.3    9.3     0
3            4   151.5      41.3       58.5   18.5     0
4            5   180.8      10.8       58.4   12.9     1

In [12]:
df.describe()

       audience_id      google    facebook   instagram       sales        size
count   200.000000  200.000000  200.000000  200.000000  200.000000  200.000000
mean    100.500000  147.042500   23.264000   30.554000   14.022500    0.540000
std      57.879185   85.854236   14.846809   21.778621    5.217457    0.499648
min       1.000000    0.700000    0.000000    0.300000    1.600000    0.000000
25%      50.750000   74.375000    9.975000   12.750000   10.375000    0.000000
50%     100.500000  149.750000   22.900000   25.750000   12.900000    1.000000
75%     150.250000  218.825000   36.525000   45.100000   17.400000    1.000000
max     200.000000  296.400000   49.600000  114.000000   27.000000    1.000000

In [13]:
target = 'sales'
inputs = ['google', 'facebook','instagram','size']

X = df[inputs]
y = df[target]

In [15]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()

lm.fit(X,y)

LinearRegression()

In [16]:
lm.score(X, y)

0.8972400790092475

In [17]:
lm.coef_

array([ 0.04571982,  0.18872814, -0.00109768,  0.05742385])

In [18]:
lm.intercept_

2.9117013282568607